# VoxelMorph training configuration

data_root: /vol/miltank/projects/practical_sose25/atlas_based_registeration/data/dataset-myelom/rawdata
split_file: /vol/miltank/projects/practical_sose25/atlas_based_registeration/subject_splits.json
split: train  # Options: train, val, test
batch_size: 1
num_workers: 4

# Training parameters
epochs: 200
learning_rate: 0.0001

# Model parameters
model:
  name: voxelmorph
  unet_features: [16, 32, 32, 32, 32, 32]  # Example feature sizes for U-Net

# Loss parameters
loss:
  similarity: mse  # Options: mse, ncc, etc.
  smoothness_weight: 1.0

# Output directory
output_dir: /vol/miltank/projects/practical_sose25/atlas_based_registeration/outputs/voxelmorph/

# Logging/checkpointing
save_every: 10  # Save model every N epochs
log_interval: 10  # Log every N batches
